global:
  imagePullSecrets:
  - aspen-mesh-pull-secret
  hub: quay.io/aspenmesh/releases
  controlPlaneSecurityEnabled: true
  mtls:
    enabled: true

  proxy:
    accessLogFile: "/dev/stdout"

  outboundTrafficPolicy:
    mode: REGISTRY_ONLY

  tracer:
    zipkin:
      # address is the Host:Port for reporting trace data in zipkin format. If
      # not specified, will default to zipkin service (port 9411) in the same
      # namespace as the other istio components.
      address: ""

galley:
  podAntiAffinityLabelSelector:
  - key: app
    operator: In
    values: galley
    topologyKey: "kubernetes.io/hostname"

  replicaCount: 2

gateways:
  istio-ingressgateway:
    autoscaleMin: 2
    podAntiAffinityLabelSelector:
    - key: app
      operator: In
      values: istio-ingressgateway
      topologyKey: "kubernetes.io/hostname"
    sds:
      enabled: true
  istio-egressgateway:
    enabled: false
    autoscaleMin: 2
    podAntiAffinityLabelSelector:
    - key: app
      operator: In
      values: istio-egressgateway
      topologyKey: "kubernetes.io/hostname"

mixer:
  policy:
    autoscaleMin: 2
    autoscaleMax: 3
    podAntiAffinityLabelSelector:
    - key: app
      operator: In
      values: policy
      topologyKey: "kubernetes.io/hostname"
  telemetry:
    autoscaleMin: 2
    autoscaleMax: 3
    podAntiAffinityLabelSelector:
    - key: app
      operator: In
      values: telemetry
      topologyKey: "kubernetes.io/hostname"

pilot:
  # Aspen Mesh has decided to disable this experimental feature until
  # both outbound and inbound protocol sniffing is merged and is
  # stable
  enableProtocolSniffingForOutbound: false
  autoscaleMin: 2
  podAntiAffinityLabelSelector:
  - key: app
    operator: In
    values: pilot
    topologyKey: "kubernetes.io/hostname"

sidecarInjectorWebhook:
  replicaCount: 2
  podAntiAffinityLabelSelector:
  - key: app
    operator: In
    values: sidecarInjectorWebhook
    topologyKey: "kubernetes.io/hostname"

security:
  replicaCount: 2
  podAntiAffinityLabelSelector:
  - key: istio
    operator: In
    values: citadel
    topologyKey: "kubernetes.io/hostname"

aspen-mesh-controlplane:
  enabled: true
  image: controlplane-1.4.6-am4
  modelruntimeImage: modelruntime-1.4.6-am4

  imagePullSecrets:
  - aspenmesh-kubernetes-pull-secret

  replicaCount: 2

  clusterId: udf-demo

  userAuth:
    type: none
    jwt:
      # jwks must provide a valid JWKs endpoint.
      jwks:
      # redirectUrl must provide an unauthenticated redirect URL.
      redirectUrl:
      # claims can be added here to require claims be present in the JWT
      # (e.g.: `claims: aud=aspenmesh:io,role=k8s:admin`).

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  modelRuntimeResources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "100m"

aspen-mesh-dashboard:
  enabled: true
  image: dashboard-1.4.6-am4
  replicaCount: 2

aspen-mesh-secure-ingress:
  enabled: true
  image: secure-ingress-1.4.6-am4
  # Email to use for Let's Encrypt registration (used for certificate expiry notices)
  # Leave blank ("") if you wish to manage your own TLS certificates.
  lets-encrypt-email: ""
  resources: {}
  externalDnsAnnotation: "policy.aspenmesh.io/externaldns"
  externalDnsEnabled: false

aspen-mesh-metrics-collector:
  serviceImage: metrics-collector-service-1.4.6-am4
  server:
    serviceResources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  alertmanagerImage: alertmanager-1.4.6-am4
  configmapReloadImage: configmap-reloader-1.4.6-am4

traffic-claim-enforcer:
  enabled: true
  image: traffic-claim-enforcer-1.4.6-am4
  resources: {}

istio_cni:
  # To enable CNI-based installations, set this to true and follow additional
  # CNI installation instructions to install the istio-cni Helm chart
  enabled: false

prometheus:
  enabled: true

cert-manager:
  enabled: true
  image:
    controller: cert-manager-controller-1.4.6-am4
    cainjector: cert-manager-cainjector-1.4.6-am4
    webhook: cert-manager-webhook-1.4.6-am4
  fullnameOverride: aspen-mesh-cert-manager

external-dns:
  image: external-dns-1.4.6-am4
  enabled: true
  fullnameOverride: aspen-mesh-external-dns

  annotationFilter: "policy.aspenmesh.io/externaldns=true"
  policy: sync
  provider: aws
  sources: ["istio-gateway"]
  txtOwnerId: aspen-mesh-secure-ingress
