---
- name: Ensure that admission webhooks are enabled in your Kubernetes cluster
  shell: "kubectl api-versions | grep -q admissionregistration"
  failed_when: admission_webhooks.rc != 0
  changed_when: false
  register: admission_webhooks

- name: Verify install Aspenmesh install path
  stat:
    path: "{{ aspenmesh_install_path }}"
  failed_when: not file_details.stat.exists
  register: file_details

- name: Check if istio-system namespace exists
  shell: "kubectl get namespaces istio-system | grep -q istio-system"
  changed_when: false
  failed_when: false
  register: istio_system_namespace

- name: Create istio-system namespace
  command: "kubectl create -f {{ aspenmesh_install_path }}/install/kubernetes/namespace.yaml"
  when: istio_system_namespace.rc != 0

- name: Check if istio-init chart exists
  shell: "helm list -n istio-system | grep -q istio-init"
  changed_when: false
  failed_when: false
  register: istio_init_chart

- name: Use helm to install the istio-init chart
  command: "helm install istio-init {{ aspenmesh_install_path }}/install/kubernetes/helm/istio-init --namespace istio-system"
  when: istio_init_chart.rc != 0

- name: Wait for Istio CRDs to become available
  wait_for:
    timeout: 20
  when: istio_init_chart.rc != 0

- name: Verify that all 23 Istio CRDs were committed to the Kubernetes apiserver
  shell: "kubectl get crds | grep 'istio.io\\|certmanager.k8s.io\\|aspenmesh.io' | wc -l"
  changed_when: false
  failed_when: istio_crd_verification.stdout <= 23
  register: istio_crd_verification

- name: Check if aspenmesh istio chart exists
  shell: "helm list -n istio-system | grep -q aspenmesh"
  changed_when: false
  failed_when: false
  register: aspenmesh_chart

- name: Copy values-aspenmesh.yml to tmp folder
  copy:
    src: values-aspenmesh.yaml
    dest: /tmp/values-aspenmesh.yaml
    mode: '0644'
  when: aspenmesh_chart.rc != 0

- name: Use helm to install the aspenmesh istio chart
  command: >
    helm install aspenmesh {{ aspenmesh_install_path }}/install/kubernetes/helm/istio
    --namespace istio-system
    --values /tmp/values-aspenmesh.yaml
  when: aspenmesh_chart.rc != 0

- name: Verify that all 26 Istio and AspenMesh CRDs were committed to the Kubernetes apiserver
  shell: "kubectl get crds | grep 'istio.io\\|certmanager.k8s.io\\|aspenmesh.io' | wc -l"
  changed_when: false
  failed_when: aspenmesh_crd_verification.stdout != "26"
  register: aspenmesh_crd_verification
