---
- name: Ensure that admission webhooks are enabled in your Kubernetes cluster.
  shell: kubectl api-versions | grep -q admissionregistration
  failed_when: admission_webhooks.rc != 0
  changed_when: false
  register: admission_webhooks

- name: Check if aspenmesh username and password are set
  fail: msg='Please source aspenmesh_credentials.sh to set the proper credentials in your local ENV'
  failed_when: 
    - lookup('env','ASPEN_MESH_USERNAME') == "" 
    - lookup('env','ASPEN_MESH_PASSWORD') is undefined

- name: Test OK.
  command: "echo {{ lookup('env','ASPEN_MESH_USERNAME') }} {{ lookup('env','ASPEN_MESH_PASSWORD') }} {{ aspenmesh_version }}"

