---
- name: Ensure that admission webhooks are enabled in your Kubernetes cluster.
  shell: kubectl api-versions | grep -q admissionregistration
  failed_when: admission_webhooks.rc != 0
  register: admission_webhooks

- name: Test OK.
  command: "echo OK"

