---
- name: Ensure that admission webhooks are enabled in your Kubernetes cluster.
  shell: kubectl api-versions | grep -q admissionregistration
  failed_when: admission_webhooks.rc != 0
  changed_when: false
  register: admission_webhooks

- name: Verify install Aspenmesh install path
  stat:
    path: "{{ aspenmesh_install_path }}"
  failed_when: not file_details.stat.exists
  register: file_details

- name: Create istio-system namespace
  command: "kubectl create -f {{ aspenmesh_install_path }}/install/kubernetes/namespace.yaml"

- name: Use helm to install the istio-init chart
  command: helm install istio-init {{ aspenmesh_install_path }}/install/kubernetes/helm/istio-init --namespace istio-system

- name: Verify that all 23 Istio CRDs were committed to the Kubernetes apiserver
  command: kubectl get crds | grep 'istio.io|certmanager.k8s.io|aspenmesh.io' | wc -l
  failed_when: aspenmesh_crd_verification.stdout != "23"
  register: aspenmesh_crd_verification
