---
- include_tasks: setup-debian.yml

- name: Ensure dependencies are installed.
  package: name=curl state=present

- name: Install kubectl
  package:
    name: kubectl
    state: present

- name: Install package that allow bash completion
  package:
    name: bash-completion
    state: present

- name: Add kubectl bash completion
  shell: /usr/bin/kubectl completion bash >/etc/bash_completion.d/kubectl
